        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:46 2014
        MODULE ASTERIODSETUPPROC__genmod
          INTERFACE 
            FUNCTION ASTERIODSETUPPROC(HDLG,MESSAGE,UPARAM,LPARAM)
              INTEGER(KIND=8) :: HDLG
              INTEGER(KIND=4) :: MESSAGE
              INTEGER(KIND=4) :: UPARAM
              INTEGER(KIND=4) :: LPARAM
              INTEGER(KIND=4) :: ASTERIODSETUPPROC
            END FUNCTION ASTERIODSETUPPROC
          END INTERFACE 
        END MODULE ASTERIODSETUPPROC__genmod
