        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:44 2014
        MODULE CENTERWINDOW__genmod
          INTERFACE 
            SUBROUTINE CENTERWINDOW(HWNDCHILD,HWNDPARENT)
              INTEGER(KIND=8) :: HWNDCHILD
              INTEGER(KIND=8) :: HWNDPARENT
            END SUBROUTINE CENTERWINDOW
          END INTERFACE 
        END MODULE CENTERWINDOW__genmod
