        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:47 2014
        MODULE GETCGLOCATION__genmod
          INTERFACE 
            SUBROUTINE GETCGLOCATION
            END SUBROUTINE GETCGLOCATION
          END INTERFACE 
        END MODULE GETCGLOCATION__genmod
