        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:47 2014
        MODULE GETSPACESHIP__genmod
          INTERFACE 
            SUBROUTINE GETSPACESHIP
            END SUBROUTINE GETSPACESHIP
          END INTERFACE 
        END MODULE GETSPACESHIP__genmod
