        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:38 2014
        MODULE GLOBALRESET__genmod
          INTERFACE 
            SUBROUTINE GLOBALRESET
            END SUBROUTINE GLOBALRESET
          END INTERFACE 
        END MODULE GLOBALRESET__genmod
