        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:44:44 2014
        MODULE GLOBALPLOTTING__genmod
          INTERFACE 
            SUBROUTINE GLOBALPLOTTING
            END SUBROUTINE GLOBALPLOTTING
          END INTERFACE 
        END MODULE GLOBALPLOTTING__genmod
