        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:41 2014
        MODULE INITIALIZEOPEN__genmod
          INTERFACE 
            FUNCTION INITIALIZEOPEN
              INTEGER(KIND=4) :: INITIALIZEOPEN
            END FUNCTION INITIALIZEOPEN
          END INTERFACE 
        END MODULE INITIALIZEOPEN__genmod
