        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:46 2014
        MODULE MAINWNDPROC__genmod
          INTERFACE 
            FUNCTION MAINWNDPROC(HWND,MESG,WPARAM,LPARAM)
              INTEGER(KIND=8) :: HWND
              INTEGER(KIND=4) :: MESG
              INTEGER(KIND=8) :: WPARAM
              INTEGER(KIND=8) :: LPARAM
              INTEGER(KIND=8) :: MAINWNDPROC
            END FUNCTION MAINWNDPROC
          END INTERFACE 
        END MODULE MAINWNDPROC__genmod
