        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:44:42 2014
        MODULE RASTER_LIST_GENERATOR__genmod
          INTERFACE 
            SUBROUTINE RASTER_LIST_GENERATOR
            END SUBROUTINE RASTER_LIST_GENERATOR
          END INTERFACE 
        END MODULE RASTER_LIST_GENERATOR__genmod
