        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:43:04 2014
        MODULE ROTATOR3D_VECTOR__genmod
          INTERFACE 
            SUBROUTINE ROTATOR3D_VECTOR(ROTATION)
              REAL(KIND=8) :: ROTATION
            END SUBROUTINE ROTATOR3D_VECTOR
          END INTERFACE 
        END MODULE ROTATOR3D_VECTOR__genmod
