        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:44:43 2014
        MODULE ROTATOR3D__genmod
          INTERFACE 
            SUBROUTINE ROTATOR3D
            END SUBROUTINE ROTATOR3D
          END INTERFACE 
        END MODULE ROTATOR3D__genmod
