        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:43:05 2014
        MODULE SETMOTION__genmod
          INTERFACE 
            SUBROUTINE SETMOTION
            END SUBROUTINE SETMOTION
          END INTERFACE 
        END MODULE SETMOTION__genmod
