        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:47 2014
        MODULE UNSTRUCTDATAGEN__genmod
          INTERFACE 
            SUBROUTINE UNSTRUCTDATAGEN
            END SUBROUTINE UNSTRUCTDATAGEN
          END INTERFACE 
        END MODULE UNSTRUCTDATAGEN__genmod
