        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:46 2014
        MODULE VEHICLESETUPPROC__genmod
          INTERFACE 
            FUNCTION VEHICLESETUPPROC(HDLG,MESSAGE,UPARAM,LPARAM)
              INTEGER(KIND=8) :: HDLG
              INTEGER(KIND=4) :: MESSAGE
              INTEGER(KIND=4) :: UPARAM
              INTEGER(KIND=4) :: LPARAM
              INTEGER(KIND=4) :: VEHICLESETUPPROC
            END FUNCTION VEHICLESETUPPROC
          END INTERFACE 
        END MODULE VEHICLESETUPPROC__genmod
