        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 13 12:35:45 2014
        MODULE WINMAIN__genmod
          INTERFACE 
            FUNCTION WINMAIN(HINSTANCE,HPREVINSTANCE,LPSZCMDLINE,       &
     &NCMDSHOW)
              INTEGER(KIND=8) :: HINSTANCE
              INTEGER(KIND=8) :: HPREVINSTANCE
              INTEGER(KIND=8) :: LPSZCMDLINE
              INTEGER(KIND=4) :: NCMDSHOW
              INTEGER(KIND=4) :: WINMAIN
            END FUNCTION WINMAIN
          END INTERFACE 
        END MODULE WINMAIN__genmod
